import type { NextPage } from "next";
import Head from "next/head";
import HomePage from "./home";

const Home: NextPage = () => {
    return (
        <div className="font-poppins">
            <Head>
                <title>Pokjar Gemilang</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="min-h-screen">
                <HomePage/>
            </main>
            <footer>
                <h1>this is footer</h1>
            </footer>
        </div>
    );
};

export default Home;
